# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------
QT += widgets
QT += websockets
QT += core
QT += gui
TEMPLATE = app
TARGET = ClockWidget_CPlusPlus
DESTDIR = ../Build_ClockWidget_CPlusPlus/x64
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(WebClientDemo.pri)
